// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRXApM6ljAH68HpCnahOxeo9caYfiu7U',
    appId: '1:554927735097:web:30e640495de7a81cf968e8',
    messagingSenderId: '554927735097',
    projectId: 'ticket-a40f9',
    authDomain: 'ticket-a40f9.firebaseapp.com',
    storageBucket: 'ticket-a40f9.appspot.com',
    measurementId: 'G-CWJGS6PQTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMSFeDpGJrTDlvc4c7MTmLLw_ZprJMm0E',
    appId: '1:554927735097:android:81d5a583a101057ef968e8',
    messagingSenderId: '554927735097',
    projectId: 'ticket-a40f9',
    storageBucket: 'ticket-a40f9.appspot.com',
  );
}
